### PR TITLE
php8 compatibility

### PR DESCRIPTION
**Pull request by nick-zh**
In PHP8 `match` is a reserved [keyword](https://wiki.php.net/rfc/match_expression_v2)

### CODE REVIEW

**Comment by nick-zh** [comment]
@widmogrod would be cool if you can have a look :v:

**Comment by widmogrod** [comment]
Hi @nick-zh , please give me some time I have to catchup to PHP8 changes. I will go back to you by the end of this week

**Comment by nick-zh** [comment]
@widmogrod yes sure thing no worries, thx for the update :+1:

**Comment by widmogrod** [comment]
Hi @nick-zh I fork your change into this feature branch https://github.com/widmogrod/php-functional/pull/107

There is few other changes necessary to make this change work with PHP8, and unfortunately not all dev dependencies are ready. 

I will experiment there to see what changes I need to introduce to enable PHP8 continuous integration. I will keep you updated.

Last' but not least, thank you for your contribution! and reminding me about this quite a big PHP release coming up soon!

**Comment by widmogrod** [comment]
@nick-zh Thank you for your contribution!

**Comment by widmogrod** [comment]
New tag 6.0.0 released

**Comment by nick-zh** [comment]
Awesome, thx a lot :tada:

**Pull request merged**
