### PR TITLE
add the `foldM` helper 

### PR DESCRIPTION
**Pull request by krtek4**
http://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Monad.html#v:foldM

contains the changes from #24 and #25

### CODE REVIEW

**Comment by widmogrod** [comment]
I will review this when https://github.com/widmogrod/php-functional/pull/24 will be merged, now is to hard to spot the differences.

**Comment by widmogrod** [comment]
Please rebase this PR

**Comment by krtek4** [comment]
Done.

**Comment by widmogrod** [comment]
After merge of PR #26 another rebase is required

**Comment by krtek4** [comment]
It is not unfortunate as it means you merged my other PR and the library is moving forward :)

It is done!

Thanks for the review.

**Review by widmogrod — APPROVED** [review]

**Comment by widmogrod** [comment]
Thank your for your contribution 🍻

**Pull request merged**
