### PR TITLE
fixing php8.4 deprecation messages

### PR DESCRIPTION
**Pull request by mihaileu**
fixing #113

### CODE REVIEW

**Comment by asanikovich** [comment]
@tPl0ch @widmogrod @nekufa @TomasVotruba @krtek4 @ilario-pierbattista
Please merge PR ASAP. Thanks

**Comment by widmogrod** [comment]
Hi @mihaileu and @asanikovich I'm preparing something bigger
https://github.com/widmogrod/php-functional/pull/115

- Switch to GH actions from Travis
- Make PHP 8.3 minimum
- Update dependencies 
- Refresh code so tests pass

You may want to take a look at it

**Comment by widmogrod** [comment]
I will merge your code, but after that will be newer version released

**Comment by widmogrod** [comment]
tag 6.0.2 released

**Pull request merged**
