### PR TITLE
fix: list & iterator return declarations

### PR DESCRIPTION
**Pull request by Deluxo**
Removes deprecation warning in PHP 8.1

### CODE REVIEW

**Comment by Deluxo** [comment]
Hey, still waiting for the merge...

**Comment by lucas-reich** [comment]
@widmogrod is there any chance that this PR will be merged? The fixes provided would be crucial for us as without them our PHP upgrade is blocked.

**Comment by lucas-reich** [comment]
Hey @widmogrod thanks a bunch for merging this one and thanks for @Deluxo for opening this MR, it really takes a lot of pain away from our upgrade :). 

@widmogrod could you also create a new release for the lib? This way we wouldn't need to depend on the `dev-master` which would be nice as it's error prone to use that one.

**Comment by widmogrod** [comment]
Sure thing @Lucas-Reich , here you have 6.0.1
https://github.com/widmogrod/php-functional/releases/tag/6.0.1

**Comment by lucas-reich** [comment]
You are the best, thank you very much :)

**Pull request merged**
